### PR TITLE
workaround asserts in mouse set_mouse_range

### PR DESCRIPTION
**Pull request by ericoporto**
- fixes wrong assert
- allow passing swapped corners

This is part of the fixes for latest Android.

### CODE REVIEW

**Comment by ghost** [comment]
Wrong assert is a mistake, which fix you may also send to the official repo, imo.
But is allowing swapped arguments essential here? Are other similar functions (that accept rect coordinates) allow same?

**Comment by ghost** [comment]
Note also, that after proposed changes asserts become useless, because function itself makes sure that the values are never wrong.

This library seem to follow guideline that a function should assert user arguments, to notify when these are wrong. That may help a programmer to notice mistake in their own code. The proposed change goes against this idea.

**Comment by ericoporto** [comment]
I will rework to fix only the assert and move needed changes to ags.

**Comment by ivan-mogilko** [comment]
Note that there was no need to close this PR, you could just ammend commit and force push the working branch.

**Pull request closed without merging**
